# Shared definition block
shared:
  # Source: https://hub.docker.com/r/library/buildpack-deps/
  image: buildpack-deps

 # Job definition block
jobs:
  main:
    requires: [~pr, ~commit]
    # Steps definition block.
    steps:
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - set-metadata: meta set example.coverage 99.95
  deploy_qa:
    requires: [main]
    steps:
      - make_target: make greetings
      - get-metadata: meta get example
      - run_arbitrary_script: echo "Create your test here"
  qa_test:
    requires: [main]
    steps:
      - run_arbitrary_script: echo "Create your test here"
  qa_certify:
      - run_arbitrary_script: echo "Create your test here"
  deploy_stg:
    requires: [main]
    steps:
      - run_arbitrary_script: echo "Create your test here"
  stg_test:
    requires: [main]
    steps:
      - run_arbitrary_script: echo "Run your stg tests here"
  stg_certify:
    requires: [main]
    steps:
      - run_arbitrary_script: echo "Stg Certify"
